Add human with meshes
robotology-playground/human-gazebo pull request #35
Opened 2024-09-03 12:49 UTC by davidegorbani

This PR adds a urdf model of a human subject with the meshes created by @Supermonkey-design.

2024-09-03 14:49 UTC, traversaro commented on CMakeLists.txt
> +install(FILES ${HUMAN_WITH_MESHES_URDF} DESTINATION ${CMAKE_INSTALL_PREFIX}/share/${PROJECT_NAME})
```suggestion
install(FILES ${HUMAN_WITH_MESHES_URDF} DESTINATION ${CMAKE_INSTALL_PREFIX}/share/${PROJECT_NAME})

```

2024-09-03 14:51 UTC, traversaro commented
I can't suggest it via the GitHub UI, but can you add a README.md to the HumanSubjectWithMeshes directory that reports that the models has been derived from https://blendswap.com/blend/11604 ?

2024-09-03 15:45 UTC, davidegorbani commented
> I can't suggest it via the GitHub UI, but can you add a README.md to the HumanSubjectWithMeshes directory that reports that the models has been derived from https://blendswap.com/blend/11604 ?

I created it.

2024-09-03 23:30 UTC, traversaro approved these changes

2024-09-03 23:30 UTC, traversaro commented on humanSubjectWithMeshes/README.md
> +The meshes in this folder has been derived from https://blendswap.com/blend/11604.
```suggestion
The meshes in this folder have been derived from https://blendswap.com/blend/11604.
```

2024-09-16 14:28 UTC, CarlottaSartore requested changes
Can you add in the main readme a line in the table for the human with meshes  ?  Thanks

2024-09-19 11:59 UTC, traversaro commented on README.md
> +In the folder [humanSubjectWithMeshes](./humanSubjectWithMeshes) there is a `urdf` model of a human sunject generated using the code in [human-model-generator](https://github.com/ami-iit/human-model-
```suggestion
In the folder [humanSubjectWithMeshes](./humanSubjectWithMeshes) there is a `urdf` model of a human subject generated using the code in [human-model-generator](https://github.com/ami-iit/human-model-generator) with meshes derived from https://blendswap.com/blend/11604.
```

2024-09-19 13:16 UTC, CarlottaSartore approved these changes
LGTM

2024-09-20 10:02 UTC, claudia-lat commented
Before merging, @davidegorbani I think that the meshes (for links and muscles), the licence and the URDF should be updated.

2024-09-24 09:05 UTC, traversaro commented
@davidegorbani would you like to be mantainer here? So you can merge when you like.

2024-09-24 12:07 UTC, traversaro commented
> @davidegorbani would you like to be mantainer here? So you can merge when you like.

You have full rights now.

2024-10-08 13:46 UTC, davidegorbani commented
Merging!

2024-10-08 13:46 UTC, merged